### ISSUE TITLE
Codebase Enhancement

### ISSUE THREAD

**Issue by ManojKiranA** [emchooo/mailness#1]
I have gone through tour Code base. and Its ok for now.

I was to contribute for Enhancement of Codebase

For Example:

https://github.com/emchooo/mailness/blob/master/app/Http/Controllers/CampaignController.php#L35

` $templates = Template::all();`

Can be Written as 

` $templates = Template::pluck('name ','id');`

Because pluck will return the array wrapped by `Collection` 

but if we are going with 

`Template::all(); `or `Template::all(['name ','id']);`

It will return the Model wrapped with Collection

And Much more i have seen. 

My Question is shall i make contribution to Mailness or Not

**Comment by emchooo** [comment]
It would be great if you could contribute.
Project is still in early dev phase, any suggestions or contributions are welcome.
