### ISSUE TITLE
Adding Status to Campaign

### ISSUE THREAD

**Issue by ManojKiranA** [emchooo/mailness#6]
I have noticed  that you are using the normal string to represent the Current status of Campaign 
:smirk: and it's not necessary we can use any of below ideas:

1.  Add enum datatype such as SENDING,DRAFT etc
2. Store as a Integer and Add the Constants that matches the value

Such as

const DRAFT = 1
const SENDING = 2
and much more.

so that we can reduce the data size.

I personally  :sunglasses: prefer the Constant and add column as integer

**Comment by emchooo** [comment]
Yes you are right. The second one sounds better. If we need to add more statuses we don't need to touch database.

**Comment by ManojKiranA** [comment]
pls label the issue as feature request
